name: GPTReviewWorkflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  review_with_gpt:
    runs-on: ubuntu-latest

    steps:
      - name: GPTReviewWorkflow
        uses: sheenhx/GPT4ReviewWorkflow@main
        with:
          GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
          GIT_PATCH_OUTPUT: ${{ github.event.pull_request.patch_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_KEY: ${{ secrets.OPENAI_ORG_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          REPOSITORY_NAME: ${{ github.repository }}
